all: blinky_dir hello_dir echo_dir spi_dir i2c_dir adc_dir input_status interrupt_dir

blinky_dir:
	$(MAKE) -C blinky

hello_dir:
	$(MAKE) -C hello

echo_dir:
	$(MAKE) -C echo

spi_dir:
	$(MAKE) -C spi

i2c_dir:
	$(MAKE) -C i2c

adc_dir:
	$(MAKE) -C adc

input_status:
	$(MAKE) -C input-status

interrupt_dir:
	$(MAKE) -C interrupt
